// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOYAqx4f7Qx_GxPOlB_uu6cTcJT3Sb-MQ',
    appId: '1:289099207166:web:696afe4bbef2370e1b30af',
    messagingSenderId: '289099207166',
    projectId: 'neuro-word',
    authDomain: 'neuro-word.firebaseapp.com',
    storageBucket: 'neuro-word.firebasestorage.app',
    measurementId: 'G-LY8LL0789C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkpltkgZ7pnzuz6si06mGHSAUB_S-ilr0',
    appId: '1:289099207166:android:8eabb4a1a0620ebc1b30af',
    messagingSenderId: '289099207166',
    projectId: 'neuro-word',
    storageBucket: 'neuro-word.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs-0Fp-XRNDkunDUQY4rxAnBL5solq24k',
    appId: '1:289099207166:ios:c721012e80403e901b30af',
    messagingSenderId: '289099207166',
    projectId: 'neuro-word',
    storageBucket: 'neuro-word.firebasestorage.app',
    iosBundleId: 'com.aphelion.plasmaAphelion',
  );

}