#!/usr/bin/env python3
"""
Generate 2000 academic English-Turkish words for Plasma Aphelion.

Usage:
    python scripts/generate_words.py

Output:
    assets/data/words.json
"""

import json, os, random

# ── Word banks by category ─────────────────────────────────────────────
# Each tuple: (english, turkish, level)
WORDS = [
    # ── Academic & Research ──────────────────────────────────────────
    ("hypothesis", "hipotez", "C1", "Academic"),
    ("methodology", "metodoloji", "C1", "Academic"),
    ("paradigm", "paradigma", "C2", "Academic"),
    ("empirical", "ampirik", "C2", "Academic"),
    ("theoretical", "teorik", "C1", "Academic"),
    ("dissertation", "tez", "C2", "Academic"),
    ("curriculum", "müfredat", "C1", "Academic"),
    ("pedagogy", "pedagoji", "C2", "Academic"),
    ("syllabus", "ders programı", "C1", "Academic"),
    ("thesis", "tez", "C1", "Academic"),
    ("bibliography", "kaynakça", "C1", "Academic"),
    ("annotation", "açıklama", "C2", "Academic"),
    ("plagiarism", "intihal", "C1", "Academic"),
    ("citation", "alıntı", "C1", "Academic"),
    ("abstract", "özet", "B2", "Academic"),
    ("appendix", "ek", "C1", "Academic"),
    ("coherent", "tutarlı", "C1", "Academic"),
    ("comprehensive", "kapsamlı", "B2", "Academic"),
    ("criterion", "kriter", "C1", "Academic"),
    ("discourse", "söylem", "C2", "Academic"),
    ("eloquent", "beliğ", "C2", "Academic"),
    ("excerpt", "alıntı", "C1", "Academic"),
    ("implicit", "örtük", "C1", "Academic"),
    ("explicit", "açık", "B2", "Academic"),
    ("inference", "çıkarım", "C1", "Academic"),
    ("scrutiny", "inceleme", "C1", "Academic"),
    ("synthesis", "sentez", "C1", "Academic"),
    ("validate", "doğrulamak", "C1", "Academic"),
    ("postulate", "varsaymak", "C2", "Academic"),
    ("corroborate", "doğrulamak", "C2", "Academic"),

    # ── Business & Finance ──────────────────────────────────────────
    ("revenue", "gelir", "B2", "Business"),
    ("expenditure", "harcama", "C1", "Business"),
    ("liability", "yükümlülük", "C1", "Business"),
    ("equity", "özsermaye", "C1", "Business"),
    ("dividend", "temettü", "C1", "Business"),
    ("merger", "birleşme", "C1", "Business"),
    ("acquisition", "satın alma", "C1", "Business"),
    ("leverage", "kaldıraç", "C2", "Business"),
    ("portfolio", "portföy", "B2", "Business"),
    ("stakeholder", "paydaş", "B2", "Business"),
    ("depreciation", "amortisman", "C1", "Business"),
    ("inflation", "enflasyon", "B2", "Business"),
    ("deflation", "deflasyon", "C1", "Business"),
    ("recession", "durgunluk", "B2", "Business"),
    ("commodity", "emtia", "C1", "Business"),
    ("tariff", "tarife", "C1", "Business"),
    ("subsidy", "sübvansiyon", "C1", "Business"),
    ("bankruptcy", "iflas", "B2", "Business"),
    ("audit", "denetim", "B2", "Business"),
    ("collateral", "teminat", "C1", "Business"),
    ("amortization", "amortisman", "C2", "Business"),
    ("benchmark", "kıyaslama", "B2", "Business"),
    ("consortium", "konsorsiyum", "C2", "Business"),
    ("entrepreneur", "girişimci", "B2", "Business"),
    ("franchise", "franchise", "B2", "Business"),
    ("incentive", "teşvik", "B2", "Business"),
    ("monopoly", "tekel", "B2", "Business"),
    ("procurement", "tedarik", "C1", "Business"),
    ("quota", "kota", "B2", "Business"),
    ("turnover", "ciro", "B2", "Business"),

    # ── Law & Governance ────────────────────────────────────────────
    ("jurisdiction", "yetki alanı", "C1", "Law"),
    ("legislation", "mevzuat", "C1", "Law"),
    ("amendment", "değişiklik", "C1", "Law"),
    ("statute", "kanun", "C1", "Law"),
    ("verdict", "karar", "B2", "Law"),
    ("litigation", "dava", "C2", "Law"),
    ("arbitration", "tahkim", "C2", "Law"),
    ("prosecution", "kovuşturma", "C1", "Law"),
    ("defendant", "sanık", "B2", "Law"),
    ("plaintiff", "davacı", "C1", "Law"),
    ("testimony", "tanıklık", "B2", "Law"),
    ("acquittal", "beraat", "C2", "Law"),
    ("compliance", "uyum", "C1", "Law"),
    ("indictment", "iddianame", "C2", "Law"),
    ("perjury", "yalancı tanıklık", "C2", "Law"),
    ("sovereignty", "egemenlik", "C1", "Law"),
    ("bureaucracy", "bürokrasi", "B2", "Law"),
    ("constitution", "anayasa", "B2", "Law"),
    ("democracy", "demokrasi", "B2", "Law"),
    ("diplomacy", "diplomasi", "B2", "Law"),
    ("embargo", "ambargo", "C1", "Law"),
    ("extradition", "iade", "C2", "Law"),
    ("jurisdiction", "yargı yetkisi", "C1", "Law"),
    ("mandate", "yetki", "C1", "Law"),
    ("ratification", "onay", "C2", "Law"),
    ("sanction", "yaptırım", "C1", "Law"),
    ("tribunal", "mahkeme", "C1", "Law"),
    ("veto", "veto", "B2", "Law"),
    ("warrant", "tutuklama emri", "C1", "Law"),
    ("abolish", "kaldırmak", "B2", "Law"),

    # ── Medicine & Health ───────────────────────────────────────────
    ("diagnosis", "teşhis", "B2", "Medicine"),
    ("prognosis", "prognoz", "C2", "Medicine"),
    ("symptom", "belirti", "B2", "Medicine"),
    ("chronic", "kronik", "B2", "Medicine"),
    ("acute", "akut", "C1", "Medicine"),
    ("inflammation", "iltihaplanma", "C1", "Medicine"),
    ("prescription", "reçete", "B2", "Medicine"),
    ("therapy", "terapi", "B2", "Medicine"),
    ("rehabilitation", "rehabilitasyon", "C1", "Medicine"),
    ("vaccination", "aşılama", "B2", "Medicine"),
    ("antibiotic", "antibiyotik", "B2", "Medicine"),
    ("pathology", "patoloji", "C2", "Medicine"),
    ("pediatrics", "pediatri", "C1", "Medicine"),
    ("cardiology", "kardiyoloji", "C1", "Medicine"),
    ("neurology", "nöroloji", "C1", "Medicine"),
    ("oncology", "onkoloji", "C1", "Medicine"),
    ("epidemiology", "epidemiyoloji", "C2", "Medicine"),
    ("immunology", "immünoloji", "C2", "Medicine"),
    ("anatomy", "anatomi", "B2", "Medicine"),
    ("physiology", "fizyoloji", "C1", "Medicine"),
    ("metabolism", "metabolizma", "B2", "Medicine"),
    ("anesthesia", "anestezi", "C1", "Medicine"),
    ("biopsy", "biyopsi", "C1", "Medicine"),
    ("contagious", "bulaşıcı", "B2", "Medicine"),
    ("dosage", "dozaj", "B2", "Medicine"),
    ("epidemic", "salgın", "B2", "Medicine"),
    ("fracture", "kırık", "B2", "Medicine"),
    ("hemorrhage", "kanama", "C2", "Medicine"),
    ("infection", "enfeksiyon", "B2", "Medicine"),
    ("syndrome", "sendrom", "C1", "Medicine"),

    # ── Technology & Computing ──────────────────────────────────────
    ("algorithm", "algoritma", "B2", "Technology"),
    ("encryption", "şifreleme", "C1", "Technology"),
    ("bandwidth", "bant genişliği", "C1", "Technology"),
    ("interface", "arayüz", "B2", "Technology"),
    ("database", "veritabanı", "B2", "Technology"),
    ("protocol", "protokol", "B2", "Technology"),
    ("firmware", "donanım yazılımı", "C1", "Technology"),
    ("middleware", "ara yazılım", "C2", "Technology"),
    ("scalability", "ölçeklenebilirlik", "C1", "Technology"),
    ("latency", "gecikme", "C1", "Technology"),
    ("authentication", "kimlik doğrulama", "C1", "Technology"),
    ("virtualization", "sanallaştırma", "C1", "Technology"),
    ("deprecated", "kullanım dışı", "C1", "Technology"),
    ("iteration", "yineleme", "C1", "Technology"),
    ("repository", "depo", "B2", "Technology"),
    ("deployment", "dağıtım", "C1", "Technology"),
    ("refactoring", "yeniden düzenleme", "C1", "Technology"),
    ("optimization", "optimizasyon", "B2", "Technology"),
    ("debugging", "hata ayıklama", "B2", "Technology"),
    ("abstraction", "soyutlama", "C1", "Technology"),
    ("binary", "ikili", "B2", "Technology"),
    ("cache", "önbellek", "B2", "Technology"),
    ("compiler", "derleyici", "C1", "Technology"),
    ("configuration", "yapılandırma", "B2", "Technology"),
    ("cybersecurity", "siber güvenlik", "B2", "Technology"),
    ("decryption", "şifre çözme", "C1", "Technology"),
    ("executable", "çalıştırılabilir", "C1", "Technology"),
    ("framework", "çerçeve", "B2", "Technology"),
    ("hardware", "donanım", "B2", "Technology"),
    ("kernel", "çekirdek", "C1", "Technology"),

    # ── Science & Research ──────────────────────────────────────────
    ("phenomenon", "fenomen", "B2", "Science"),
    ("hypothesis", "varsayım", "C1", "Science"),
    ("catalyst", "katalizör", "C1", "Science"),
    ("entropy", "entropi", "C2", "Science"),
    ("quantum", "kuantum", "C2", "Science"),
    ("molecule", "molekül", "B2", "Science"),
    ("organism", "organizma", "B2", "Science"),
    ("ecosystem", "ekosistem", "B2", "Science"),
    ("evolution", "evrim", "B2", "Science"),
    ("photosynthesis", "fotosentez", "B2", "Science"),
    ("chromosome", "kromozom", "C1", "Science"),
    ("isotope", "izotop", "C2", "Science"),
    ("fusion", "füzyon", "C1", "Science"),
    ("fission", "fisyon", "C2", "Science"),
    ("spectrum", "spektrum", "C1", "Science"),
    ("velocity", "hız", "B2", "Science"),
    ("acceleration", "ivme", "B2", "Science"),
    ("gravity", "yerçekimi", "B2", "Science"),
    ("thermodynamics", "termodinamik", "C2", "Science"),
    ("biochemistry", "biyokimya", "C1", "Science"),
    ("astronomy", "astronomi", "B2", "Science"),
    ("archaeology", "arkeoloji", "B2", "Science"),
    ("botany", "botanik", "C1", "Science"),
    ("geology", "jeoloji", "B2", "Science"),
    ("meteorology", "meteoroloji", "C1", "Science"),
    ("paleontology", "paleontoloji", "C2", "Science"),
    ("zoology", "zooloji", "B2", "Science"),
    ("genetics", "genetik", "B2", "Science"),
    ("microbiology", "mikrobiyoloji", "C1", "Science"),
    ("nanotechnology", "nanoteknoloji", "C1", "Science"),

    # ── Psychology & Sociology ──────────────────────────────────────
    ("cognition", "biliş", "C1", "Psychology"),
    ("perception", "algı", "B2", "Psychology"),
    ("stimulus", "uyaran", "C1", "Psychology"),
    ("neurosis", "nevroz", "C2", "Psychology"),
    ("psychotherapy", "psikoterapi", "C1", "Psychology"),
    ("empathy", "empati", "B2", "Psychology"),
    ("resilience", "dayanıklılık", "B2", "Psychology"),
    ("anxiety", "kaygı", "B2", "Psychology"),
    ("trauma", "travma", "B2", "Psychology"),
    ("phobia", "fobi", "B2", "Psychology"),
    ("altruism", "özgecilik", "C2", "Psychology"),
    ("conformity", "uyum", "C1", "Psychology"),
    ("deviance", "sapma", "C2", "Psychology"),
    ("socialization", "sosyalleşme", "C1", "Psychology"),
    ("stratification", "tabakalaşma", "C2", "Psychology"),
    ("assimilation", "asimilasyon", "C1", "Psychology"),
    ("demographic", "demografik", "B2", "Psychology"),
    ("stereotype", "kalıp yargı", "B2", "Psychology"),
    ("prejudice", "önyargı", "B2", "Psychology"),
    ("discrimination", "ayrımcılık", "B2", "Psychology"),
    ("autonomous", "özerk", "C1", "Psychology"),
    ("behavioral", "davranışsal", "C1", "Psychology"),
    ("cognitive", "bilişsel", "C1", "Psychology"),
    ("consciousness", "bilinç", "C1", "Psychology"),
    ("delusion", "sanrı", "C2", "Psychology"),
    ("extrovert", "dışa dönük", "B2", "Psychology"),
    ("introvert", "içe dönük", "B2", "Psychology"),
    ("instinct", "içgüdü", "B2", "Psychology"),
    ("motivation", "motivasyon", "B2", "Psychology"),
    ("subconscious", "bilinçaltı", "C1", "Psychology"),

    # ── Environment & Ecology ───────────────────────────────────────
    ("sustainability", "sürdürülebilirlik", "B2", "Environment"),
    ("biodiversity", "biyoçeşitlilik", "C1", "Environment"),
    ("conservation", "koruma", "B2", "Environment"),
    ("deforestation", "ormansızlaşma", "B2", "Environment"),
    ("emissions", "emisyonlar", "B2", "Environment"),
    ("renewable", "yenilenebilir", "B2", "Environment"),
    ("fossil", "fosil", "B2", "Environment"),
    ("contamination", "kirlilik", "C1", "Environment"),
    ("erosion", "erozyon", "B2", "Environment"),
    ("habitat", "yaşam alanı", "B2", "Environment"),
    ("ozone", "ozon", "B2", "Environment"),
    ("carbon", "karbon", "B2", "Environment"),
    ("greenhouse", "sera", "B2", "Environment"),
    ("pesticide", "pestisit", "C1", "Environment"),
    ("recycle", "geri dönüştürmek", "B2", "Environment"),
    ("drought", "kuraklık", "B2", "Environment"),
    ("glacier", "buzul", "B2", "Environment"),
    ("watershed", "havza", "C1", "Environment"),
    ("aquifer", "akifer", "C2", "Environment"),
    ("permafrost", "permafrost", "C2", "Environment"),
    ("afforestation", "ağaçlandırma", "C1", "Environment"),
    ("biodegradable", "biyolojik olarak parçalanabilir", "C1", "Environment"),
    ("compost", "kompost", "B2", "Environment"),
    ("desertification", "çölleşme", "C1", "Environment"),
    ("endangered", "nesli tükenmekte", "B2", "Environment"),
    ("extinction", "yok oluş", "B2", "Environment"),
    ("herbicide", "herbisit", "C1", "Environment"),
    ("irrigation", "sulama", "B2", "Environment"),
    ("landfill", "çöp sahası", "C1", "Environment"),
    ("pollutant", "kirletici", "C1", "Environment"),

    # ── Philosophy & Ethics ─────────────────────────────────────────
    ("epistemology", "epistemoloji", "C2", "Philosophy"),
    ("ontology", "ontoloji", "C2", "Philosophy"),
    ("metaphysics", "metafizik", "C2", "Philosophy"),
    ("existentialism", "varoluşçuluk", "C2", "Philosophy"),
    ("utilitarianism", "faydacılık", "C2", "Philosophy"),
    ("nihilism", "nihilizm", "C2", "Philosophy"),
    ("stoicism", "stoacılık", "C2", "Philosophy"),
    ("pragmatism", "pragmatizm", "C1", "Philosophy"),
    ("determinism", "determinizm", "C2", "Philosophy"),
    ("relativism", "görecilik", "C2", "Philosophy"),
    ("altruistic", "özgecil", "C1", "Philosophy"),
    ("benevolent", "hayırsever", "C1", "Philosophy"),
    ("conscience", "vicdan", "B2", "Philosophy"),
    ("dilemma", "ikilem", "B2", "Philosophy"),
    ("ethical", "etik", "B2", "Philosophy"),
    ("integrity", "dürüstlük", "B2", "Philosophy"),
    ("morality", "ahlak", "B2", "Philosophy"),
    ("virtue", "erdem", "C1", "Philosophy"),
    ("wisdom", "bilgelik", "B2", "Philosophy"),
    ("paradox", "paradoks", "C1", "Philosophy"),
    ("ambiguity", "belirsizlik", "C1", "Philosophy"),
    ("analogy", "benzetme", "C1", "Philosophy"),
    ("axiom", "aksiyom", "C2", "Philosophy"),
    ("contradiction", "çelişki", "B2", "Philosophy"),
    ("dogma", "dogma", "C1", "Philosophy"),
    ("fallacy", "safsata", "C2", "Philosophy"),
    ("ideology", "ideoloji", "B2", "Philosophy"),
    ("logic", "mantık", "B2", "Philosophy"),
    ("rationalism", "rasyonalizm", "C2", "Philosophy"),
    ("skepticism", "şüphecilik", "C1", "Philosophy"),

    # ── Art & Literature ────────────────────────────────────────────
    ("aesthetic", "estetik", "B2", "Art"),
    ("allegory", "alegori", "C2", "Art"),
    ("metaphor", "metafor", "C1", "Art"),
    ("irony", "ironi", "B2", "Art"),
    ("satire", "hiciv", "C1", "Art"),
    ("narrative", "anlatı", "B2", "Art"),
    ("protagonist", "baş kahraman", "C1", "Art"),
    ("antagonist", "hasım", "C1", "Art"),
    ("genre", "tür", "B2", "Art"),
    ("anthology", "antoloji", "C2", "Art"),
    ("contemporary", "çağdaş", "B2", "Art"),
    ("renaissance", "rönesans", "B2", "Art"),
    ("avant-garde", "avangard", "C2", "Art"),
    ("composition", "kompozisyon", "B2", "Art"),
    ("improvisation", "doğaçlama", "C1", "Art"),
    ("choreography", "koreografi", "C1", "Art"),
    ("typography", "tipografi", "C1", "Art"),
    ("calligraphy", "kaligrafi", "C1", "Art"),
    ("architecture", "mimarlık", "B2", "Art"),
    ("sculpture", "heykel", "B2", "Art"),
    ("abstract", "soyut", "B2", "Art"),
    ("baroque", "barok", "C1", "Art"),
    ("curator", "küratör", "C1", "Art"),
    ("exhibition", "sergi", "B2", "Art"),
    ("gallery", "galeri", "B2", "Art"),
    ("masterpiece", "başyapıt", "B2", "Art"),
    ("mosaic", "mozaik", "B2", "Art"),
    ("portrait", "portre", "B2", "Art"),
    ("sketch", "eskiz", "B2", "Art"),
    ("symbolism", "sembolizm", "C1", "Art"),

    # ── Engineering ─────────────────────────────────────────────────
    ("tolerance", "tolerans", "B2", "Engineering"),
    ("calibration", "kalibrasyon", "C1", "Engineering"),
    ("specification", "şartname", "C1", "Engineering"),
    ("prototype", "prototip", "B2", "Engineering"),
    ("turbine", "türbin", "C1", "Engineering"),
    ("hydraulic", "hidrolik", "C1", "Engineering"),
    ("pneumatic", "pnömatik", "C2", "Engineering"),
    ("alloy", "alaşım", "C1", "Engineering"),
    ("composite", "kompozit", "C1", "Engineering"),
    ("conductivity", "iletkenlik", "C1", "Engineering"),
    ("aerodynamics", "aerodinamik", "C1", "Engineering"),
    ("corrosion", "korozyon", "C1", "Engineering"),
    ("fatigue", "yorulma", "C1", "Engineering"),
    ("insulation", "yalıtım", "B2", "Engineering"),
    ("lubrication", "yağlama", "C1", "Engineering"),
    ("oscillation", "salınım", "C2", "Engineering"),
    ("resonance", "rezonans", "C1", "Engineering"),
    ("tensile", "çekme", "C2", "Engineering"),
    ("viscosity", "viskozite", "C2", "Engineering"),
    ("welding", "kaynak", "B2", "Engineering"),
    ("amplifier", "yükselteç", "C1", "Engineering"),
    ("capacitor", "kapasitör", "C1", "Engineering"),
    ("circuit", "devre", "B2", "Engineering"),
    ("diode", "diyot", "C1", "Engineering"),
    ("electrode", "elektrot", "C1", "Engineering"),
    ("generator", "jeneratör", "B2", "Engineering"),
    ("semiconductor", "yarı iletken", "C1", "Engineering"),
    ("thermostat", "termostat", "B2", "Engineering"),
    ("transformer", "transformatör", "C1", "Engineering"),
    ("voltage", "voltaj", "B2", "Engineering"),

    # ── Linguistics ─────────────────────────────────────────────────
    ("phonetics", "fonetik", "C1", "Linguistics"),
    ("morphology", "morfoloji", "C2", "Linguistics"),
    ("syntax", "söz dizimi", "C1", "Linguistics"),
    ("semantics", "anlambilim", "C1", "Linguistics"),
    ("pragmatics", "pragmatik", "C2", "Linguistics"),
    ("etymology", "etimoloji", "C1", "Linguistics"),
    ("dialect", "lehçe", "B2", "Linguistics"),
    ("bilingual", "iki dilli", "B2", "Linguistics"),
    ("fluency", "akıcılık", "B2", "Linguistics"),
    ("colloquial", "konuşma dili", "C1", "Linguistics"),
    ("acronym", "kısaltma", "B2", "Linguistics"),
    ("connotation", "çağrışım", "C1", "Linguistics"),
    ("denotation", "düz anlam", "C1", "Linguistics"),
    ("euphemism", "örtmece", "C1", "Linguistics"),
    ("homonym", "eşsesli", "C1", "Linguistics"),
    ("idiom", "deyim", "B2", "Linguistics"),
    ("jargon", "jargon", "B2", "Linguistics"),
    ("lexicon", "sözlük", "C1", "Linguistics"),
    ("monolingual", "tek dilli", "C1", "Linguistics"),
    ("multilingual", "çok dilli", "B2", "Linguistics"),
    ("neologism", "yeni sözcük", "C2", "Linguistics"),
    ("onomatopoeia", "yansıma", "C2", "Linguistics"),
    ("palindrome", "palindrom", "C2", "Linguistics"),
    ("proverb", "atasözü", "B2", "Linguistics"),
    ("rhetoric", "retorik", "C1", "Linguistics"),
    ("slang", "argo", "B2", "Linguistics"),
    ("synonym", "eşanlamlı", "B2", "Linguistics"),
    ("antonym", "zıt anlamlı", "B2", "Linguistics"),
    ("verb", "fiil", "B2", "Linguistics"),
    ("conjunction", "bağlaç", "B2", "Linguistics"),

    # ── Economics & Politics ────────────────────────────────────────
    ("capitalism", "kapitalizm", "B2", "Economics"),
    ("socialism", "sosyalizm", "B2", "Economics"),
    ("communism", "komünizm", "B2", "Economics"),
    ("liberalism", "liberalizm", "B2", "Economics"),
    ("globalization", "küreselleşme", "B2", "Economics"),
    ("privatization", "özelleştirme", "C1", "Economics"),
    ("nationalization", "kamulaştırma", "C1", "Economics"),
    ("deregulation", "deregülasyon", "C2", "Economics"),
    ("austerity", "kemer sıkma", "C1", "Economics"),
    ("fiscal", "mali", "C1", "Economics"),
    ("monetary", "parasal", "C1", "Economics"),
    ("surplus", "fazla", "B2", "Economics"),
    ("deficit", "açık", "B2", "Economics"),
    ("taxation", "vergilendirme", "B2", "Economics"),
    ("allocation", "tahsis", "C1", "Economics"),
    ("bilateral", "ikili", "C1", "Economics"),
    ("coalition", "koalisyon", "B2", "Economics"),
    ("constituency", "seçim bölgesi", "C1", "Economics"),
    ("dictatorship", "diktatörlük", "B2", "Economics"),
    ("electorate", "seçmen", "C1", "Economics"),
    ("federation", "federasyon", "B2", "Economics"),
    ("geopolitics", "jeopolitik", "C1", "Economics"),
    ("hegemony", "hegemonya", "C2", "Economics"),
    ("imperialism", "emperyalizm", "C1", "Economics"),
    ("nationalism", "milliyetçilik", "B2", "Economics"),
    ("oligarchy", "oligarşi", "C2", "Economics"),
    ("populism", "popülizm", "C1", "Economics"),
    ("referendum", "referandum", "B2", "Economics"),
    ("totalitarianism", "totalitarizm", "C2", "Economics"),
    ("annexation", "ilhak", "C2", "Economics"),

    # ── Architecture & Urban Planning ───────────────────────────────
    ("infrastructure", "altyapı", "B2", "Architecture"),
    ("sustainability", "sürdürülebilirlik", "B2", "Architecture"),
    ("facade", "cephe", "C1", "Architecture"),
    ("elevation", "yükseklik", "B2", "Architecture"),
    ("blueprint", "plan", "B2", "Architecture"),
    ("foundation", "temel", "B2", "Architecture"),
    ("renovation", "tadilat", "B2", "Architecture"),
    ("demolition", "yıkım", "C1", "Architecture"),
    ("urbanization", "kentleşme", "B2", "Architecture"),
    ("zoning", "imar", "C1", "Architecture"),
    ("acoustic", "akustik", "C1", "Architecture"),
    ("cantilever", "konsol", "C2", "Architecture"),
    ("corridor", "koridor", "B2", "Architecture"),
    ("dome", "kubbe", "B2", "Architecture"),
    ("edifice", "yapı", "C2", "Architecture"),
    ("fenestration", "pencere düzeni", "C2", "Architecture"),
    ("masonry", "duvar işçiliği", "C1", "Architecture"),
    ("parapet", "parapet", "C2", "Architecture"),
    ("pillar", "sütun", "B2", "Architecture"),
    ("vault", "tonoz", "C1", "Architecture"),

    # ── Communication & Media ───────────────────────────────────────
    ("propaganda", "propaganda", "B2", "Media"),
    ("censorship", "sansür", "B2", "Media"),
    ("journalism", "gazetecilik", "B2", "Media"),
    ("editorial", "başyazı", "C1", "Media"),
    ("broadcast", "yayın", "B2", "Media"),
    ("circulation", "tiraj", "C1", "Media"),
    ("correspondent", "muhabir", "C1", "Media"),
    ("headline", "manşet", "B2", "Media"),
    ("publication", "yayın", "B2", "Media"),
    ("tabloid", "bulvar gazetesi", "C1", "Media"),
    ("advertisement", "reklam", "B2", "Media"),
    ("audience", "izleyici", "B2", "Media"),
    ("commentary", "yorum", "B2", "Media"),
    ("documentary", "belgesel", "B2", "Media"),
    ("freelance", "serbest", "B2", "Media"),
    ("infographic", "infografik", "B2", "Media"),
    ("mainstream", "ana akım", "B2", "Media"),
    ("newsletter", "bülten", "B2", "Media"),
    ("podcast", "podcast", "B2", "Media"),
    ("syndication", "sendikasyon", "C2", "Media"),

    # ── Diplomacy & International Relations ─────────────────────────
    ("treaty", "antlaşma", "B2", "Diplomacy"),
    ("alliance", "ittifak", "B2", "Diplomacy"),
    ("ceasefire", "ateşkes", "B2", "Diplomacy"),
    ("negotiation", "müzakere", "B2", "Diplomacy"),
    ("mediation", "arabuluculuk", "C1", "Diplomacy"),
    ("reconciliation", "uzlaşma", "C1", "Diplomacy"),
    ("asylum", "sığınma", "C1", "Diplomacy"),
    ("deportation", "sınır dışı etme", "C1", "Diplomacy"),
    ("immigration", "göç", "B2", "Diplomacy"),
    ("refugee", "mülteci", "B2", "Diplomacy"),
    ("ambassador", "büyükelçi", "B2", "Diplomacy"),
    ("consulate", "konsolosluk", "C1", "Diplomacy"),
    ("delegation", "heyet", "C1", "Diplomacy"),
    ("envoy", "elçi", "C2", "Diplomacy"),
    ("humanitarian", "insani", "B2", "Diplomacy"),
    ("intervention", "müdahale", "B2", "Diplomacy"),
    ("multilateral", "çok taraflı", "C1", "Diplomacy"),
    ("neutrality", "tarafsızlık", "C1", "Diplomacy"),
    ("peacekeeping", "barış gücü", "B2", "Diplomacy"),
    ("protocol", "protokol", "B2", "Diplomacy"),

    # ── Mathematics & Statistics ────────────────────────────────────
    ("equation", "denklem", "B2", "Mathematics"),
    ("variable", "değişken", "B2", "Mathematics"),
    ("coefficient", "katsayı", "C1", "Mathematics"),
    ("probability", "olasılık", "B2", "Mathematics"),
    ("deviation", "sapma", "C1", "Mathematics"),
    ("correlation", "korelasyon", "C1", "Mathematics"),
    ("regression", "regresyon", "C2", "Mathematics"),
    ("theorem", "teorem", "C1", "Mathematics"),
    ("logarithm", "logaritma", "C1", "Mathematics"),
    ("integral", "integral", "C1", "Mathematics"),
    ("derivative", "türev", "C1", "Mathematics"),
    ("matrix", "matris", "C1", "Mathematics"),
    ("vector", "vektör", "C1", "Mathematics"),
    ("polynomial", "polinom", "C1", "Mathematics"),
    ("permutation", "permütasyon", "C2", "Mathematics"),
    ("asymptote", "asimptot", "C2", "Mathematics"),
    ("calculus", "kalkülüs", "C1", "Mathematics"),
    ("circumference", "çevre", "B2", "Mathematics"),
    ("diameter", "çap", "B2", "Mathematics"),
    ("exponent", "üs", "C1", "Mathematics"),
    ("factorial", "faktöriyel", "C1", "Mathematics"),
    ("fraction", "kesir", "B2", "Mathematics"),
    ("geometry", "geometri", "B2", "Mathematics"),
    ("hypotenuse", "hipotenüs", "C1", "Mathematics"),
    ("inequality", "eşitsizlik", "B2", "Mathematics"),
    ("median", "medyan", "B2", "Mathematics"),
    ("numerator", "pay", "C1", "Mathematics"),
    ("denominator", "payda", "C1", "Mathematics"),
    ("ratio", "oran", "B2", "Mathematics"),
    ("trigonometry", "trigonometri", "C1", "Mathematics"),

    # ── Additional Academic Vocabulary ──────────────────────────────
    ("alleviate", "hafifletmek", "C1", "General"),
    ("ambivalent", "kararsız", "C1", "General"),
    ("arbitrary", "keyfi", "C1", "General"),
    ("benign", "iyi huylu", "C1", "General"),
    ("candid", "açık sözlü", "C1", "General"),
    ("capricious", "kaprisli", "C2", "General"),
    ("coerce", "zorlamak", "C1", "General"),
    ("complacent", "kayıtsız", "C1", "General"),
    ("concede", "kabul etmek", "C1", "General"),
    ("condone", "göz yummak", "C2", "General"),
    ("conspicuous", "göze çarpan", "C1", "General"),
    ("contemplate", "düşünmek", "C1", "General"),
    ("conventional", "geleneksel", "B2", "General"),
    ("debilitate", "zayıflatmak", "C2", "General"),
    ("defamation", "iftira", "C2", "General"),
    ("defer", "ertelemek", "C1", "General"),
    ("delineate", "betimlemek", "C2", "General"),
    ("denounce", "kınamak", "C1", "General"),
    ("deplete", "tüketmek", "C1", "General"),
    ("deteriorate", "kötüleşmek", "C1", "General"),
    ("digress", "konudan sapmak", "C2", "General"),
    ("diligent", "çalışkan", "B2", "General"),
    ("diminish", "azaltmak", "C1", "General"),
    ("discrepancy", "tutarsızlık", "C1", "General"),
    ("disdain", "küçümsemek", "C2", "General"),
    ("disparity", "eşitsizlik", "C1", "General"),
    ("disseminate", "yaymak", "C1", "General"),
    ("elicit", "ortaya çıkarmak", "C1", "General"),
    ("embody", "somutlaştırmak", "C1", "General"),
    ("encompass", "kapsamak", "C1", "General"),
    ("endeavor", "çaba", "C1", "General"),
    ("enhance", "geliştirmek", "B2", "General"),
    ("enumerate", "saymak", "C2", "General"),
    ("erratic", "düzensiz", "C1", "General"),
    ("exacerbate", "kötüleştirmek", "C2", "General"),
    ("exemplify", "örneklemek", "C1", "General"),
    ("feasible", "uygulanabilir", "C1", "General"),
    ("fluctuate", "dalgalanmak", "C1", "General"),
    ("formidable", "zorlu", "C1", "General"),
    ("fortuitous", "tesadüfi", "C2", "General"),
    ("frivolous", "anlamsız", "C2", "General"),
    ("gregarious", "sosyal", "C2", "General"),
    ("haphazard", "gelişigüzel", "C1", "General"),
    ("hinder", "engellemek", "B2", "General"),
    ("imminent", "yakın", "C1", "General"),
    ("impede", "engellemek", "C1", "General"),
    ("imperative", "zorunlu", "C1", "General"),
    ("incite", "kışkırtmak", "C1", "General"),
    ("indifferent", "kayıtsız", "B2", "General"),
    ("inevitable", "kaçınılmaz", "B2", "General"),
    ("infer", "çıkarım yapmak", "C1", "General"),
    ("inhibit", "engellemek", "C1", "General"),
    ("innate", "doğuştan", "C1", "General"),
    ("innovative", "yenilikçi", "B2", "General"),
    ("instigate", "tahrik etmek", "C2", "General"),
    ("intangible", "soyut", "C1", "General"),
    ("intermittent", "aralıklı", "C1", "General"),
    ("intrinsic", "özünde olan", "C1", "General"),
    ("juxtapose", "yan yana koymak", "C2", "General"),
    ("lucrative", "kazançlı", "C1", "General"),
    ("meticulous", "titiz", "C1", "General"),
    ("mitigate", "hafifletmek", "C1", "General"),
    ("mundane", "sıradan", "C1", "General"),
    ("negate", "geçersiz kılmak", "C1", "General"),
    ("negligible", "önemsiz", "C1", "General"),
    ("novel", "yeni", "B2", "General"),
    ("nuance", "nüans", "C1", "General"),
    ("obscure", "belirsiz", "C1", "General"),
    ("obsolete", "modası geçmiş", "C1", "General"),
    ("omit", "ihmal etmek", "B2", "General"),
    ("opaque", "opak", "C1", "General"),
    ("permeate", "nüfuz etmek", "C2", "General"),
    ("perpetuate", "sürdürmek", "C2", "General"),
    ("pertinent", "ilgili", "C1", "General"),
    ("plausible", "makul", "C1", "General"),
    ("precarious", "tehlikeli", "C1", "General"),
    ("precede", "öncesinde olmak", "C1", "General"),
    ("predominant", "baskın", "C1", "General"),
    ("profound", "derin", "C1", "General"),
    ("proliferate", "çoğalmak", "C2", "General"),
    ("propensity", "eğilim", "C2", "General"),
    ("provoke", "kışkırtmak", "B2", "General"),
    ("redundant", "gereksiz", "B2", "General"),
    ("refute", "çürütmek", "C1", "General"),
    ("relinquish", "bırakmak", "C2", "General"),
    ("replenish", "yeniden doldurmak", "C1", "General"),
    ("repudiate", "reddetmek", "C2", "General"),
    ("resilient", "dirençli", "B2", "General"),
    ("restrain", "kısıtlamak", "C1", "General"),
    ("retain", "tutmak", "B2", "General"),
    ("revoke", "iptal etmek", "C1", "General"),
    ("robust", "sağlam", "B2", "General"),
    ("scrutinize", "incelemek", "C1", "General"),
    ("secular", "laik", "C1", "General"),
    ("sparse", "seyrek", "C1", "General"),
    ("speculate", "spekülasyon yapmak", "C1", "General"),
    ("spontaneous", "kendiliğinden", "B2", "General"),
    ("stagnant", "durgun", "C1", "General"),
    ("stringent", "katı", "C1", "General"),
    ("substantiate", "kanıtlamak", "C2", "General"),
    ("subtle", "ince", "B2", "General"),
    ("superfluous", "gereksiz", "C2", "General"),
    ("surpass", "aşmak", "C1", "General"),
    ("tangible", "somut", "C1", "General"),
    ("tenacious", "inatçı", "C2", "General"),
    ("tentative", "geçici", "C1", "General"),
    ("trivial", "önemsiz", "C1", "General"),
    ("ubiquitous", "her yerde bulunan", "C2", "General"),
    ("unanimous", "oybirliği", "C1", "General"),
    ("undermine", "baltalamak", "C1", "General"),
    ("unprecedented", "emsalsiz", "C1", "General"),
    ("unwarranted", "haksız", "C1", "General"),
    ("viable", "uygulanabilir", "C1", "General"),
    ("volatile", "değişken", "C1", "General"),
    ("vulnerable", "savunmasız", "B2", "General"),
    ("warrant", "garanti etmek", "C1", "General"),
    ("yield", "verim", "B2", "General"),
    ("zealous", "gayretli", "C2", "General"),
]


def deduplicate(words):
    """Remove duplicate English words, keeping first occurrence."""
    seen = set()
    unique = []
    for w in words:
        key = w[0].lower()
        if key not in seen:
            seen.add(key)
            unique.append(w)
    return unique


def generate_json(target_count=2000):
    """Generate the words JSON file."""
    unique_words = deduplicate(WORDS)

    # Build base entries
    entries = []
    for i, (eng, tur, level, cat) in enumerate(unique_words, 1):
        entries.append({
            "id": i,
            "english": eng,
            "turkish": tur,
            "level": level,
            "category": cat,
            "isLearned": False,
        })

    actual = len(entries)
    print(f"Generated {actual} unique words from the word bank.")

    if actual < target_count:
        print(f"Note: {target_count - actual} more words needed to reach {target_count}.")
        print("Add more tuples to the WORDS list and re-run.")

    # Write JSON
    script_dir = os.path.dirname(os.path.abspath(__file__))
    output = os.path.join(script_dir, "..", "assets", "data", "words.json")
    output = os.path.normpath(output)

    with open(output, "w", encoding="utf-8") as f:
        json.dump(entries, f, ensure_ascii=False, indent=2)

    print(f"Wrote {actual} words to {output}")


if __name__ == "__main__":
    generate_json()
