const List<Map<String, dynamic>> kAcademicWordSamples = [
  {
    'en': 'ability',
    'tr': 'yetenek',
    'level': 'A1',
    'source': 'oxford_3000',
    'difficultyWeight': 1,
    'category': 'Noun',
    'pos': 'n.',
  },
  {
    'en': 'communicate',
    'tr': 'iletişim kurmak',
    'level': 'A1',
    'source': 'awl',
    'difficultyWeight': 3,
    'category': 'Verb',
    'pos': 'v.',
  },
  {
    'en': 'culture',
    'tr': 'kültür',
    'level': 'A2',
    'source': 'awl',
    'difficultyWeight': 4,
    'category': 'Noun',
    'pos': 'n.',
  },
  {
    'en': 'environment',
    'tr': 'çevre',
    'level': 'A2',
    'source': 'awl',
    'difficultyWeight': 4,
    'category': 'Noun',
    'pos': 'n.',
  },
  {
    'en': 'design',
    'tr': 'tasarım',
    'level': 'A2',
    'source': 'oxford_3000',
    'difficultyWeight': 2,
    'category': 'Noun',
    'pos': 'n.',
  },
  {
    'en': 'consequence',
    'tr': 'sonuç',
    'level': 'B1',
    'source': 'oxford_5000',
    'difficultyWeight': 5,
    'category': 'Noun',
    'pos': 'n.',
  },
  {
    'en': 'analysis',
    'tr': 'analiz',
    'level': 'B1',
    'source': 'awl',
    'difficultyWeight': 6,
    'category': 'Noun',
    'pos': 'n.',
  },
  {
    'en': 'strategy',
    'tr': 'strateji',
    'level': 'B1',
    'source': 'awl',
    'difficultyWeight': 6,
    'category': 'Noun',
    'pos': 'n.',
  },
  {
    'en': 'phenomenon',
    'tr': 'fenomen',
    'level': 'B2',
    'source': 'oxford_5000',
    'difficultyWeight': 7,
    'category': 'Noun',
    'pos': 'n.',
  },
  {
    'en': 'hypothesis',
    'tr': 'hipotez',
    'level': 'B2',
    'source': 'awl',
    'difficultyWeight': 8,
    'category': 'Noun',
    'pos': 'n.',
  },
  {
    'en': 'substantial',
    'tr': 'önemli',
    'level': 'B2',
    'source': 'awl',
    'difficultyWeight': 8,
    'category': 'Adjective',
    'pos': 'adj.',
  },
  {
    'en': 'paradigm',
    'tr': 'paradigma',
    'level': 'C1',
    'source': 'oxford_5000',
    'difficultyWeight': 8,
    'category': 'Noun',
    'pos': 'n.',
  },
  {
    'en': 'methodology',
    'tr': 'metodoloji',
    'level': 'C1',
    'source': 'awl',
    'difficultyWeight': 10,
    'category': 'Noun',
    'pos': 'n.',
  },
  {
    'en': 'scrutinize',
    'tr': 'incelemek',
    'level': 'C1',
    'source': 'awl',
    'difficultyWeight': 10,
    'category': 'Verb',
    'pos': 'v.',
  },
  {
    'en': 'unprecedented',
    'tr': 'eşi görülmemiş',
    'level': 'C1',
    'source': 'oxford_5000',
    'difficultyWeight': 8,
    'category': 'Adjective',
    'pos': 'adj.',
  },
];

const Map<String, Map<String, int>> kDifficultyWeightMatrix = {
  'awl': {
    'A1': 3,
    'A2': 4,
    'B1': 6,
    'B2': 8,
    'C1': 10,
  },
  'oxford_5000': {
    'A1': 2,
    'A2': 3,
    'B1': 5,
    'B2': 7,
    'C1': 8,
  },
  'oxford_3000': {
    'A1': 1,
    'A2': 2,
    'B1': 3,
    'B2': 5,
    'C1': 6,
  },
};
